routes/web.php
<?php

use App\Http\Controllers\FileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('files');
    // return view('welcome');
});

Route::resource('files', FileController::class);

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * Get all of the headings for the File
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function headings()
    {
        return $this->hasMany(FileHeading::class);
    }
}

app/Models/FileHeading.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FileHeading extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'file_id', 'name', 'key'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];
}

app/Models/FileRow.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FileRow extends Model
{
    use HasFactory;

     /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'file_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * Get all of the rowsData for the FileRow
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rowsData()
    {
        return $this->hasMany(RowData::class);
    }
}

app/Models/RowData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RowData extends Model
{
    use HasFactory;

     /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'row_id', 'value', 'key'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\Repository\Eloquent\BaseRepository;
use App\Services\FileService;
use Illuminate\Http\Request;
use App\Models\File;

class FileController extends Controller
{

    protected $service;
    private $repository;

    public function __construct()
    {
        $this->repository = new BaseRepository(new File());
        $this->service=new FileService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('index', ['files'=>$this->repository->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [ 
            'file' => 'required|mimes:csv,xlsx,xls,text/csv,txt'
        ]);
        
        return $this->service->import($request->file('file'), $this->repository);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        return $this->service->get($request->all(), $id, $this->repository);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/create.blade.php
@extends('welcome')
@section('content')

<div class="card mt-5">
    <div class="card-header">
        <a type="button" href="{{ route('files.index') }}" class="btn btn-outline-dark btn-loader">Back</a>
    </div>
    <div class="card-body">
        <h5 class="card-title">Upload File</h5>
        
        @if ($errors->count() > 0)
        <div role="alert" class="alert alert-block alert-danger">
            <button type="button" class="close close-sm" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>

            @foreach ($errors->messages() as $message)
            <p>{{ $message[0] }}</p>
            @endforeach
        </div>
        @endif

        <form action="{{route('files.store')}}" method="post" id="file-form" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleFormControlFile1"></label>
                <input type="file" name="file" class="form-control-file" id="exampleFormControlFile1" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
            </div>
            <button type="submit" class="btn btn-primary btn-loader" id="load2" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Processing Order">Upload</button>
        </form>
    </div>
</div>

@endsection

resources/views/index.blade.php
@extends('welcome')
@section('content')

<div class="card mt-5">
    <div class="card-header">
        <a href="{{ route('files.create') }}" class="btn btn-outline-dark btn-loader">Upload</a>
    </div>
    <div class="card-body">
        @if(Session::has('success_message'))
            <div class="alert alert-block alert-success">
                <button type="button" class="close close-sm" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <p> {{ Session::get('success_message') }} </p>
            </div>
        @endif
        <h5 class="card-title">Files</h5>
        <table class="table table-bordered mb-5">
            <thead>
                <tr class="table-success">
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col" width="150px">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($files as $file)
                <tr>
                    <th scope="row">{{ $file->id }}</th>
                    <td>{{ $file->name }}</td>
                    <td><a href="{{ route('files.show', $file->id) }}" class="btn btn-primary btn-loader">View</a></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</section>


@endsection

resources/views/show.blade.php
@extends('welcome')
@section('content')

<div class="mt-5">
    <div class="ml-3">
        <a href="{{ route('files.index') }}" class="btn btn-outline-dark  btn-loader">Back</a>
    </div>
    <div class="card-body">
        <h5 class="card-title">{{$file->name}}</h5>
        <table class="table table-bordered mb-5">
            <thead>
                <tr class="table-success">
                    <!-- <th scope="col">#</th> -->
                    @foreach($file->headings AS $heading)
                    <th scope="col">{{$heading->name}}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($list as $row)
                <tr>
                    <!-- <th scope="row">{{ $row->id }}</th> -->
                    @foreach($row->rowsData AS $data)
                        <td>{{ $data->value }}</td>
                    @endforeach
                </tr>
                @endforeach
            </tbody>
        </table>

        <nav aria-label="...">
            <ul class="pagination pagination-lg">
                <?php 
                    $currentPage = $list->currentPage();
                    $perPage = $list->perPage();
                    $lastPage = $list->lastPage();
                ?>
                @for($i=1; $i<=$lastPage; $i++)
                    <li class="page-item {{$i==$currentPage?'disabled':''}}"><a  tabindex="{{$i==$currentPage?'-1':''}}" class="page-link" href="{{route('files.show', $file->id . '?page=' . $i )}}">{{$i}}</a></li>
                @endfor
            </ul>
        </nav>

    </div>
</section>
@endsection